version: '3'

services:
  mongo:
    container_name: rmd_mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  backend:
    container_name: rmd_backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8008:8008"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=prod -Dspring.data.mongodb.password=${MONGO_PASSWORD} -Dspring.app.serverHost=${SERVER_HOST}
    depends_on:
      - mongo
  frontend:
    container_name: rmd_frontend
    build:
      context: ../rmd_front
      dockerfile: Dockerfile
    ports:
      - "8009:80"
    restart: always
  prerender:
    container_name: rmd_prerender
    image: lune/prerender
    ports:
      - "4000:3000"
    restart: always

