version: '3'

services:
  mongo:
    container_name: rmd_mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  frontend:
    container_name: rmd_frontend
    build:
      context: ../rmd_front
      dockerfile: Dockerfile
    ports:
      - "80:80"
  backend:
    container_name: rmd_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:8008"