server:
  port: 8008

spring:
  app:
    serverHost: ${SERVER_HOST:http://localhost:8008}
    jwtAuthSecret: ${JWT_AUTH_SECRET:defaultsecret_11111111111111111111}
  data:
    mongodb:
      username: ${MONGO_USERNAME:root}
      password: ${MONGO_PASSWORD:defaultpass}
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:rmd}
      authentication-database: ${MONGO_AUTHENTICATION_DATABASE:admin}