server:
  port: 8008

spring:
  app:
    serverHost: http://localhost:8008
  data:
    mongodb:
      username: root
      host: localhost
      port: 27017
      database: rmd
      authentication-database: admin